// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXlRUIshdEoHEOhlWNI86LKIBvx1ctds',
    appId: '1:831200671886:web:aa0e1e5d5477d47b6c71df',
    messagingSenderId: '831200671886',
    projectId: 'appnotifications-5e0a9',
    authDomain: 'appnotifications-5e0a9.firebaseapp.com',
    databaseURL: 'https://appnotifications-5e0a9.firebaseio.com',
    storageBucket: 'appnotifications-5e0a9.appspot.com',
    measurementId: 'G-HD67LHM10V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzMFVz4nrLYcLDtLlRTki_hwaMdio3caA',
    appId: '1:831200671886:android:439eed1a689152346c71df',
    messagingSenderId: '831200671886',
    projectId: 'appnotifications-5e0a9',
    databaseURL: 'https://appnotifications-5e0a9.firebaseio.com',
    storageBucket: 'appnotifications-5e0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcEo0pVArnjaHFFJorb0FBcd6_fbfGNDI',
    appId: '1:831200671886:ios:562d25428212bfb06c71df',
    messagingSenderId: '831200671886',
    projectId: 'appnotifications-5e0a9',
    databaseURL: 'https://appnotifications-5e0a9.firebaseio.com',
    storageBucket: 'appnotifications-5e0a9.appspot.com',
    iosBundleId: 'com.example.connexionFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcEo0pVArnjaHFFJorb0FBcd6_fbfGNDI',
    appId: '1:831200671886:ios:562d25428212bfb06c71df',
    messagingSenderId: '831200671886',
    projectId: 'appnotifications-5e0a9',
    databaseURL: 'https://appnotifications-5e0a9.firebaseio.com',
    storageBucket: 'appnotifications-5e0a9.appspot.com',
    iosBundleId: 'com.example.connexionFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqXlRUIshdEoHEOhlWNI86LKIBvx1ctds',
    appId: '1:831200671886:web:0e5edad5b6e33d716c71df',
    messagingSenderId: '831200671886',
    projectId: 'appnotifications-5e0a9',
    authDomain: 'appnotifications-5e0a9.firebaseapp.com',
    databaseURL: 'https://appnotifications-5e0a9.firebaseio.com',
    storageBucket: 'appnotifications-5e0a9.appspot.com',
    measurementId: 'G-C3TTK5Y6LH',
  );
}
